git clone https://github.com/eic/fun4all_coresoftware
git clone https://github.com/eic/fun4all_tutorials
git clone https://github.com/eic/fun4all_macros
git clone https://github.com/eic/online_distribution
git clone https://github.com/eic/fun4all_acts
git clone https://github.com/eic/g4lblvtx
git clone https://github.com/eic/g4exampledetector
git clone https://github.com/eic/fun4all_g4jleic
git clone https://github.com/eic/Fun4All-lmon
git clone https://github.com/eic/fun4all_GenFit
git clone https://github.com/eic/BeastMagneticField
git clone https://github.com/eic/PEPSI
git clone https://github.com/eic/eic-smear
git clone https://github.com/eic/eicsmear-jetexample
git clone https://github.com/eic/fun4all_eicdetectors
git clone https://github.com/eic/fun4all_eic_tutorials
git clone https://github.com/eic/eicsmeardetectors
git clone https://github.com/eic/EicRoot
git clone https://github.com/eic/delphes_EIC
git clone https://github.com/eic/EicToyModel
